### PR TITLE
A map using javascript

### PR DESCRIPTION
**Pull request by mitul3737**
Creating a map

### CODE REVIEW

**Comment by ljharb** [comment]
Please don't spam for Hacktoberfest.

**Comment by mitul3737** [comment]
It is not...I just used codepen website..kindly accept..you can check if
you doubt please

**Comment by ljharb** [comment]
I agree that your code does what it says, but how would that snippet of code be useful here, in Airbnb's JavaScript style guide? This is not a repo for code snippets.

**Comment by mitul3737** [comment]
Okay

**Pull request closed without merging**
