### PR TITLE
Use Array.from to convert arguments to array

### PR DESCRIPTION
**Pull request by silvenon**
You recommended that technique before. Or is that hurting the point? Is `prototype.slice.call` intentionally used to make the bad example worse?

### CODE REVIEW

**Comment by geekjuice** [comment]
Might be a tangential argument, but [`Array#from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) doesn't seem to have very good support yet, so using `Array::slice` is safer. With that in mind, I would also argue [4.4](https://github.com/airbnb/javascript#4.4) should be updated to `[...foo]`.

**Comment by ljharb** [comment]
The style guide is written assuming that the [es5-shim](https://github.com/es-shims/es5-shim) and [es6-shim](https://github.com/paulmillr/es6-shim) are being used, so availability of the API isn't a problem.

However, this particular example is meant to convey how an ES5 pattern can be improved with an ES6 pattern - `Array.from`, I think, would lessen that impact.

**Comment by geekjuice** [comment]
Ah, didn't realize those shims were used. Carry on :rocket:

**Comment by silvenon** [comment]
Ok :+1:

**Pull request closed without merging**
