### PR TITLE
generate test cases from our styleguide's README.md

### PR DESCRIPTION
**Pull request by justjake**
WORK IN PROGRESS
1. get all the code blocks from the styleguide README.md
2. split out examples based on `// bad`, `// good`, `// best` comments
3. prepend common setup code that occurs before each delimiters to each
   example
4. test each example:
   - all examples must be valid Javascript code according to ESLint using
     our config.
   - good examples must lint without errors or warnings
   - best examples must lint without errors or warnings
   - bad examples must fail linting

In the next commits, I plan to edit README.md to reduce the number of examples with irregular delimiters  like `// good - bla bla bla bla bla`

### CODE REVIEW

**Comment by ljharb** [comment]
Sweet, this LGTM

**Comment by mmwtsn** [comment]
This is great.

If that functionality is at all reusable being able to extract JavaScript in GitHub-flavored Markdown blocks from a project's README to lint would be a useful npm module to have outside this repo.

**Comment by justjake** [comment]
@mmwtsn I'll see what ends up general enough to package. I'm considering splitting the README up into multiple documents with more annotation around the test cases and slightly easier formatting. I'm also considering writing some python-doctest inspired stuff to verify `// -> [1, 2]` style value annotations

**Comment by justjake** [comment]
alright i have a format for styleguide sections that I'm pretty happy with; the main feature is no more manually tracking rule numbers and tables of contents.

Here's a demo of building from the easy section format to the existing markdown format
```
> airbnb-style@2.0.0 script /home/justjake/src/javascript
> babel-node ./script/index.js




INPUT MARKDOWN TEXT:
# Destructuring

## Use object destructuring when accessing and using multiple properties of an object.

> Why? Destructuring saves you from creating temporary references for those
> properties.

```javascript
// bad
function getFullName(user) {
  const firstName = user.firstName;
  const lastName = user.lastName;

  return `${firstName} ${lastName}`;
}

// good
function getFullName(obj) {
  const { firstName, lastName } = obj;
  return `${firstName} ${lastName}`;
}

// best
function getFullName({ firstName, lastName }) {
  return `${firstName} ${lastName}`;
}
```

## Use array destructuring.

```javascript
const arr = [1, 2, 3, 4];

// bad
const first = arr[0];
const second = arr[1];

// good
const [first, second] = arr;
```

## Use object destructuring for multiple return values, not array destructuring.

> Why? You can add new properties over time or change the order of things
> without breaking call sites.

```javascript
// bad
function processInput(input) {
  // then a miracle occurs
  return [left, right, top, bottom];
}

// the caller needs to think about the order of return data
const [left, __, top] = processInput(input);

// good
function processInput(input) {
  // then a miracle occurs
  return { left, right, top, bottom };
}

// the caller selects only the data they need
const { left, right } = processInput(input);
```




ORIGINAL:
root[9]
├─ heading[1]
│  └─ text: 'Destructuring'
├─ heading[1]
│  └─ text: 'Use object destructuring when accessing and using multiple properties of an object.'
├─ blockquote[1]
│  └─ paragraph[1]
│     └─ text: 'Why? Destructuring saves you from creating temporary references for those
properties.'
├─ code: '(elided)'
├─ heading[1]
│  └─ text: 'Use array destructuring.'
├─ code: '(elided)'
├─ heading[1]
│  └─ text: 'Use object destructuring for multiple return values, not array destructuring.'
├─ blockquote[1]
│  └─ paragraph[1]
│     └─ text: 'Why? You can add new properties over time or change the order of things
without breaking call sites.'
└─ code: '(elided)'



GROUPED:
root[1]
└─ ext.OutlineSection[3]
   ├─ ext.OutlineSection[2]
   │  ├─ blockquote[1]
   │  │  └─ paragraph[1]
   │  │     └─ text: 'Why? Destructuring saves you from creating temporary references for those
properties.'
   │  └─ code: '(elided)'
   ├─ ext.OutlineSection[1]
   │  └─ code: '(elided)'
   └─ ext.OutlineSection[2]
      ├─ blockquote[1]
      │  └─ paragraph[1]
      │     └─ text: 'Why? You can add new properties over time or change the order of things
without breaking call sites.'
      └─ code: '(elided)'



STYLING:
root[1]
└─ ext.Styleguide[1]
   └─ ext.Section: 'Destructuring'



BACK BABY:
root[3]
├─ heading[1]
│  └─ text: 'Destructuring'
├─ list[3]
│  ├─ listItem[3]
│  │  ├─ paragraph[6]
│  │  │  ├─ link[1]
│  │  │  │  └─ text: '1.1'
│  │  │  ├─ text: ' '
│  │  │  ├─ html: '<a name="1.1">'
│  │  │  ├─ html: '</a>'
│  │  │  ├─ text: ' '
│  │  │  └─ text: 'Use object destructuring when accessing and using multiple properties of an object.'
│  │  ├─ blockquote[1]
│  │  │  └─ paragraph[1]
│  │  │     └─ text: 'Why? Destructuring saves you from creating temporary references for those
properties.'
│  │  └─ code: '(elided)'
│  ├─ listItem[2]
│  │  ├─ paragraph[6]
│  │  │  ├─ link[1]
│  │  │  │  └─ text: '1.2'
│  │  │  ├─ text: ' '
│  │  │  ├─ html: '<a name="1.2">'
│  │  │  ├─ html: '</a>'
│  │  │  ├─ text: ' '
│  │  │  └─ text: 'Use array destructuring.'
│  │  └─ code: '(elided)'
│  └─ listItem[3]
│     ├─ paragraph[6]
│     │  ├─ link[1]
│     │  │  └─ text: '1.3'
│     │  ├─ text: ' '
│     │  ├─ html: '<a name="1.3">'
│     │  ├─ html: '</a>'
│     │  ├─ text: ' '
│     │  └─ text: 'Use object destructuring for multiple return values, not array destructuring.'
│     ├─ blockquote[1]
│     │  └─ paragraph[1]
│     │     └─ text: 'Why? You can add new properties over time or change the order of things
without breaking call sites.'
│     └─ code: '(elided)'
└─ link[1]
   └─ text: '⬆ back to top'



AND VIOLA:
## Destructuring

-   [1.1](#1.1) <a name="1.1"></a> Use object destructuring when accessing and using multiple properties of an object.

    > Why? Destructuring saves you from creating temporary references for those
    > properties.

    ```javascript
    (elided)
    ```

-   [1.2](#1.2) <a name="1.2"></a> Use array destructuring.

    ```javascript
    (elided)
    ```

-   [1.3](#1.3) <a name="1.3"></a> Use object destructuring for multiple return values, not array destructuring.

    > Why? You can add new properties over time or change the order of things
    > without breaking call sites.

    ```javascript
    (elided)
    ```

[⬆ back to top](#table-of-contents)
```

**Comment by ariporad** [comment]
Hey, @justjake, I've been looking at this PR for a while, and I think it's really awesome. I was wondering what the status on it was?

I'm going to go look through it now, and see if I could figure out a way to help (if you'd like that).

Thanks again!

**Comment by justjake** [comment]
@ariporad sure if you're feeling generous. I worked on this a couple weekends in a row when I had no plans. I got a bit carried away with a side-project to rewrite the README as a bunch of seperate markdown documents with a more reasonable format -- I hate having to maintain indentation and manually ordering things.

So, there are two things going on in this PR really: I started with the test extraction stuff, but then I moved on to Markdown AST manipulation and generating .md documents from other .md documents.

I'm not actively working on this idea any more because styleguide meddling is hard to justify to myself over my other projects. I still think re-organizing the guide and producing tests from the styleguide itself is a worthwhile endeavor.

If I were to start working on this branch again, I would first write a script to automatically create the section markdown files from the existing (master) README.md since there have been many changes to the master styleguide.

Then, I would clean up the styleguide representational classes to make extracting test cases easier.
Finally, I would use the styleguide generation classes to re-write https://github.com/airbnb/javascript/pull/480/files#diff-92afd690ee7051d5486860c89df391f5R1 so there's just one way of parsing markdowns into styleguide classes and working with them.

**Comment by ariporad** [comment]
Hmm...

If it's OK with you, I'm going to try a simpler way of combining README files, so more focus can be done on the test cases. If possible, I'd even like to auto-generate the .eslintrc, as opposed to the tests.

**Comment by justjake** [comment]
:+1:

**Comment by ljharb** [comment]
When we're ready to reattempt this, we should use eslint-plugin-markdown for it.

**Pull request closed without merging**
