### PR TITLE
Bump copyright year 2016 -> 2017 in license

### PR DESCRIPTION
**Pull request by lencioni**
Welcome to the new year! 🎊

### CODE REVIEW

**Comment by fvgs** [comment]
Perhaps we should do "2016-present"?

**Comment by ericblade** [comment]
@fvgs i'm not an expert on these sort of things, but all the policies i've worked under required me to update every copyright in every file either the entire source-tree at once, or when and only when a file had other specific changes made to it during that year.  I don't think "present" works legally.

**Comment by fvgs** [comment]
@ericblade I have no legal expertise, but I've seen this being done by Facebook in many of their repositories e.g. [React](https://github.com/facebook/react/blob/master/LICENSE), [Jest](https://github.com/facebook/jest/blob/master/LICENSE)

**Comment by ljharb** [comment]
I'm pretty certain that "legally" is satisfied by "copyright 2010", and that you don't need to specify the "ending year" - the copyright once declared lasts until it expires.

**Comment by ericblade** [comment]
... but that could be losing 7 years of copyright protection if not updated. :-)   of course, copyright protection varies drastically by region, always good to have lawyers for these sorts of things

**Comment by ljharb** [comment]
@ericblade no, that's what I'm saying. "copyright 2010" gives copyright protection for like 85 years or something. The `- 2017` is never required.

**Comment by hshoff** [comment]
Just wanted to clarify, the style guide was started in 2012 https://github.com/airbnb/javascript/commit/cab510342f93791a7487d16258d06ff73edb4507

**Pull request merged**
