### PR TITLE
fixing readme title

### PR DESCRIPTION
**Pull request by KelltonHamaia**
Setting a better named title for this repo.

### CODE REVIEW

**Comment by KelltonHamaia** [comment]
Just testing, I'm studying this tool - Sry

**Comment by ljharb** [comment]
It’s not testing, it’s spam.

**Comment by KelltonHamaia** [comment]
Sorry. It was really a test, as I said, I am studying a crash course of git
and github, and that was the content of the class, about pull requests and
forks.

Em sex., 5 de jan. de 2024 12:48, Jordan Harband ***@***.***>
escreveu:

**Comment by ljharb** [comment]
Can you link me to the class? It’s generating lots of spam and I’d like to reach out to the instructor.

**Pull request closed without merging**
