### PR TITLE
Change Batman to Superman

### PR DESCRIPTION
**Pull request by steveosneu**
Not sure if this is how to do this.  Please reconsider.  Superman is much better fit for this style guide.  I beg you merge.

### CODE REVIEW

**Comment by ljharb** [comment]
Superman is just being his normal Kryptonian self. Batman actually had to *work* to be a superhero.

Of course, both of them think the way to solve societal problems is to go around punching individual criminals.

In what way is Superman a better fit?

**Comment by steveosneu** [comment]
http://youtu.be/uqiMY7nIBbI

Thanks.  Please watch this.  It convinced me.

**Comment by ljharb** [comment]
http://youtu.be/UeEQAvkU5x0 is a pretty convincing counterpoint.

**Comment by goatslacker** [comment]
This change is one that the JavaScript community deserves, but not the one it needs right now. So we'll close this. Because GitHub can take it. Because it's not our changeset.

**Comment by hshoff** [comment]
```js
[Array(8).join('Superman' - 1),'Batman!'].join(' ');
```

**Pull request closed without merging**
