### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cihat**
used my repo style guide

### CODE REVIEW

**Comment by cihat** [comment]
I used the style guide in my own warehouse. I added this to the readme

**Comment by ljharb** [comment]
@cihat plesse restore this branch and reopen this PR.

**Comment by cihat** [comment]
sorry, I'm just learning github. I think I did it wrong. I am in the learning phase. Thanks for be interested.

**Comment by cihat** [comment]
Meanwhile, I deleted the repo that I forked. I can't open branch from it again.

**Comment by ljharb** [comment]
If you re-fork it, and recreate the new branch at 27ce4b5, then you should be able to reopen the PR.

**Comment by cihat** [comment]
Thank you for your interest in me.

**Pull request closed without merging**
