### PR TITLE
Adding jeopardybot to styleguide users.

### PR DESCRIPTION
**Pull request by kesne**
This adds arguably the most important consumer of the glorious AirB&B Styleguide ever.

### CODE REVIEW

**Comment by ljharb** [comment]
What is "merge"?

**Comment by philihp** [comment]
So this list now includes products as well as organizations?

**Comment by ljharb** [comment]
that's a fair point, but i think we can make an exception for this case

**Comment by philihp** [comment]
I, for one, welcome our new Trebek overlords.

**Comment by jimrhoskins** [comment]
Resolution is simple, incorporate JeopardyBot LLC.

**Pull request merged**
