### PR TITLE
[eslint] restructure eslint-config-airbnb, move .eslintrc

### PR DESCRIPTION
**Pull request by justjake**
It's frustrating to try to package airbnb-style and eslint-config-airbnb together just to update eslint-config-airbnb.

This PR moves the .eslintrc file into the airbnb-config-eslint package but preserves the old location with a symlink for backwards compatibility. It also restructures eslint-config-airbnb to use peerDependencies for the ESlint react plugin and babel-eslint, as proposed in #415.

Is moving this file a good idea? You tell me.

### CODE REVIEW

**Comment by ljharb** [comment]
strong -1 on anything that *increases* use of peer deps :-(

**Comment by justjake** [comment]
what is wrong with peerdeps?

**Comment by justjake** [comment]
ok i'll just blow up all the deps

**Comment by hshoff** [comment]
I enjoy this very much.

**Pull request merged**
