### PR TITLE
Make reassigning a separate rule.

### PR DESCRIPTION
**Pull request by AlicanC**
Made the change discussed in #641.

### CODE REVIEW

**Comment by ljharb** [comment]
I'm not sure why GH is unable to show the diff here :-/ However, it looks good on my machine.

**Comment by AlicanC** [comment]
I have said that `no-param-reassign` has nothing to do with mutation, but it looks like it does:
https://github.com/eslint/eslint/blob/master/docs/rules/no-param-reassign.md

Setting `props` to `true` should also prevent parameter mutation and it's enabled in Airbnb config:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/best-practices.js#L79

The weird thing is, ESLint doesn't warn me when I do this:
```javascript
function f(obj) {
  obj.key = 1;
}

f({ key: 1 });
```

Am I misreading the rule? What is wrong here?

**Comment by ljharb** [comment]
hm, it should give you an error when doing that. that might be an `eslint` bug?

**Comment by AlicanC** [comment]
Hmm, the change was actually made in https://github.com/airbnb/javascript/commit/2589c67b0c392a118aba3e3938856ddfead26baa which is yet to be released. It should work when it's released.

---

I think putting these under separate rules is still a good idea. I could add the same `eslint rules:` indication to "Never mutate parameters." since it will also covered by that rule on the next release.

If having two Airbnb rules pointing to the same ESLint rule would be weird, I could merge the rules again under "Never reassign or mutate parameters." and keep the "It can also cause optimization issues, especially in V8." part.

**Comment by ljharb** [comment]
I like having a separate section for `no-param-reassign`. Multiple rules in one guide section is fine, but ideally each rule is only in one guide section.

**Comment by AlicanC** [comment]
So we merge this one and we are done?
https://github.com/AlicanC/javascript/commit/a5030475badd272e0ca3d3562fa18d8f14194ad8

It looks like this PR won't update itself since it's merged. I'm supposed to create another PR right?

**Comment by ljharb** [comment]
yes, you'd need to make a new PR once the original is merged, on a new branch.

**Pull request merged**
