### PR TITLE
Japanese Translation for Readme Link

### PR DESCRIPTION
**Pull request by WataruKay**

### CODE REVIEW

**Comment by sotayamashita** [comment]
@ljharb I am Japanese and it looks good :smile:

**Comment by ljharb** [comment]
@sotayamashita thanks!

@WataruKay would you please check the "allow maintainers to edit" checkbox, so I can rebase and merge this?

**Comment by WataruKay** [comment]
@sotayamashita Thank you for reviewing :smile: 

@ljharb It seems like a Japanese translation has already been added to the react readme, so I will close this pr.

**Comment by ljharb** [comment]
@WataruKay oops, thanks, sorry about that.

**Pull request closed without merging**
