### PR TITLE
match documentation: allow underscore dangle after this

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
http://airbnb.io/javascript/#22.4

```js
  // good
  this._firstName = 'Panda';
```

**Comment by ljharb** [comment]
Definitely not - the documentation should be updated. Leading underscores are not permitted.

**Comment by graingert** [comment]
@ljharb what should the documentation be updated to?

**Comment by ljharb** [comment]
Ah - airbnb.io is the older (not-updated) copy. https://github.com/airbnb/javascript#naming--leading-underscore is what's up to date.

**Comment by ljharb** [comment]
I've updated airbnb.io - sorry for the inconvenience.

**Pull request closed without merging**
