### PR TITLE
Added Quizes with solutions

### PR DESCRIPTION
**Pull request by mthirumalai29**
Iam sorry for the trouble @ljharb My old account got suspended some how so am raising a PR From this one whenever you get the leisure time Please review it and let me know about it 😊

### CODE REVIEW

**Comment by ljharb** [comment]
Please don't submit duplicate PRs; you can comment a link on the original one - especially considering this wasn't supposed to be a PR in the first place.

**Comment by ljharb** [comment]
I think I'm going to just say that this isn't appropriate content for this guide, and I'd encourage you to post it elsewhere - perhaps we can link to it.

Duplicate of #2958.

**Comment by mthirumalai29** [comment]
@ljharb am really sorry i dont know my github account got suspended and i have a interview coming up is there anyways we can recover the account

**Comment by ljharb** [comment]
You'd have to ask github that.

**Comment by mthirumalai29** [comment]
Yes i will try

**Pull request closed without merging**
