### PR TITLE
Bump version of eslint-plugin-import

### LINKED ISSUE #2002: Why is the definition of a variable is moved after using?
The require of the `package.json` is moved later — the resulting code will not work

Why such code:
```js
const pkg = require('../package.json')

if (!process.version !== pkg.engines.node) { /* .. */ }

const app = require('yargs')
const updateNotifier = require('update-notifier')
```

will be turned into such:
```js
 
if (!process.version !== pkg.engines.node) { /* .. */ }

const app = require('yargs');
const updateNotifier = require('update-notifier');
const pkg = require('../package.json');
```

I use MacOS, `node@10.10.0`, `npm@6.4.1`, `eslint@5.13.0`, `eslint-config-airbnb-base@13.1.0`

### PR DESCRIPTION
**Pull request by aboyton**
This fixes a bug with moving around variable definitions.

Fixes #2002 and  #1980

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks, but `^2.15.0` already includes `v2.16` via the semver range, so this isn't necessary.

**Comment by aboyton** [comment]
That is true, people can always bump the version themselves and it's consistent with the semantic range that you have set (as you recommended in #2002).

But correct me if I'm wrong if people are using `package-lock.json` (or `yarn.lock`) and they've installed a while ago then they will pin to `2.15.0` and `npm ls` won't let them know that there's any issues even though they have a buggy version of `eslint-plugin-import`, where as if you bump the version and people upgrade `eslint-config-airbnb` then it will be more obvious to them. Honest question, I'm curious what's better here from a library standpoint.

**Comment by ljharb** [comment]
By using a lockfile, you've signed yourself up for running `npm outdated` (or using greenkeeper, or any other means of finding out when there's updates), and manually doing those updates.

I agree that before the next release we'll want to bump the version, but bumping deps is usually done by maintainers as prep for the release process.

**Comment by aboyton** [comment]
Thanks for the explanation. Feel free to either leave this around as a reminder or close it, whatever is most helpful for you.

**Pull request closed without merging**
