### PR TITLE
New feature for Classes and Objects definition

### PR DESCRIPTION
**Pull request by teamcreed**
It is very important to consider OOP, because one of the most important aspects writing maintainable code is being able to notice the recurring themes in that code and optimize them.

### CODE REVIEW

**Comment by goatslacker** [comment]
https://github.com/airbnb/javascript#constructors

**Comment by goatslacker** [comment]
We should probably rename that to Classes.

**Comment by teamcreed** [comment]
Yes, you can rename it 

are pattern designs considered in this guide?

**Comment by ljharb** [comment]
Pattern designs that we use at Airbnb are definitely worth including.

In this case, a constructor function that isn't an ES6 "class" contradicts https://github.com/airbnb/javascript#constructors, so I think this needs to be closed as-is.

**Pull request closed without merging**
