### PR TITLE
4.7 layout problem, be better

### PR DESCRIPTION
**Pull request by ZweiZhao**
have not change any code, only add a tab.

### CODE REVIEW

**Comment by ljharb** [comment]
What's the benefit of adding this tab?

**Comment by ZweiZhao** [comment]
Markdown rules that the contents of the sequence should have a tab indentation.
README.md other parts have tab indentation, only there is not.

**Comment by ljharb** [comment]
Hmm. Is there some kind of linting tool we could use that would prevent this from regressing in the future?

**Comment by ZweiZhao** [comment]
Sadly, no.
Just a layout problem, not a grammar issue.

**Pull request merged**
