### PR TITLE
Delete keys in README.md

### PR DESCRIPTION
**Pull request by LuiSilvak**
Leaving a more beautiful head title to the README of this repo.

### CODE REVIEW

**Comment by LuiSilvak** [comment]
Just testing

**Comment by ljharb** [comment]
No, you're not just testing, you're spamming and making the internet worse. Test on *your own* repos, not those that don't belong to you.

**Comment by LuiSilvak** [comment]
Sorry for just doing a TEST. Thank you very much for your wonderful answer, congratulations!

**Comment by ljharb** [comment]
You're not the first person with almost this exact PR, so whatever this is is clearly not just a test.

Duplicate of #2839. Duplicate of #2848. Duplicate of #2855.

**Pull request closed without merging**
