### PR TITLE
Added Descriptors

### PR DESCRIPTION
**Pull request by mthirumalai2905**
I have added descriptors below the Objects thought it might be helpfull since its one of the most important property which let us know and have a deep knowledge about why some values can be changes and why some are not it helps us undesrtanding the encapuslation of it too

please review the PR and go ahead make some chnages if you want to make it look as the standard readme add some eslint dos and dont and mozilla links too

thank you !!!!
Looking forward to contribute more

### CODE REVIEW

**Comment by mthirumalai2905** [comment]
Can anyone please help me how to check "Allow Edits" im a beginner

**Comment by ljharb** [comment]
@mthirumalai2905 you can't - because you made a PR from "not your personal fork", it can't ever pass. Also, PRs are best not made from master.

This is also a duplicate of #2952 and a duplicate of #2953.

It's best to discuss significant changes with an issue before filing one PR, let alone three, and in this case, I don't think it belongs in this guide - it's not general documentation of JavaScript; that's for MDN.

**Comment by mthirumalai2905** [comment]
Thank you sir it was really helpful 👍 

So we have to make a personal fork from our account's repo then push 

But before we make a PR we should post a issue 

Am I correct sir?

**Comment by ljharb** [comment]
> So we have to make a personal fork from our account's repo then push

yes, don't make a PR from a company fork.

> But before we make a PR we should post a issue

that will depend on the repo, and on the change, but in general it's always safest to start with an issue.

**Pull request closed without merging**
