### PR TITLE
no-empty-label was renamed to no-labels in ESLint v2

### PR DESCRIPTION
**Pull request by silvenon**
eslint/eslint#5129

### CODE REVIEW

**Comment by silvenon** [comment]
Didn't see #711.

**Comment by ljharb** [comment]
Thanks for the contribution! Currently we're still on v1.x.

I'll be updating to v2.0 at the same time as updating all these rules. Accepting this as-is would break everyone using the package, which currently requires 1.x and does not work with 2.x.

**Comment by silvenon** [comment]
Yeah, I didn't do my research :sweat_smile:

**Comment by ljharb** [comment]
Tracked in #730

**Pull request closed without merging**
