### PR TITLE
Update readme with yarn usage

### PR DESCRIPTION
**Pull request by gblejman**

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks for the contribution! Not only do I not think this is accurate (I think yarn has a command to install the peer deps for you), but yarn isn't quite production ready yet, and Airbnb is not yet recommending it's use.

**Comment by hkdobrev** [comment]
@ljharb Do you think AirBnB is open to recommending Yarn usage now as it has a greater adoption now and is a bit more mature? Thanks!

**Comment by ljharb** [comment]
No, it's still not fully production-ready.

**Comment by oshalygin** [comment]
@hkdobrev there have been a number of reported issues(some of which I've experienced myself) when using private NPM repositories and yarn.

**Pull request closed without merging**
