### PR TITLE
[spam]

### PR DESCRIPTION
**Pull request by 2001Navneet**
hey,you can ignore this PR. I did this to teach my friend how to raise PR.

### CODE REVIEW

**Comment by ljharb** [comment]
Then you taught your friend how to spam.

**Comment by 2001Navneet** [comment]
> Then you taught your friend how to spam.
can't you read properly what i've written to" ignore this PR."why would i spam there is nothing in that file.

**Comment by ljharb** [comment]
@2001Navneet the PR itself is spam. you don't get to decide what other people ignore - if you want it ignored, make a PR on your own repo and ignore it.

**Comment by 2001Navneet** [comment]
My bad brother , thanks for your suggestion .

**Pull request closed without merging**
