### PR TITLE
[eslint config] [deps] update `eslint-plugin-react-hooks`

### PR DESCRIPTION
**Pull request by ptmkenny**
[eslint-plugin-react-hooks had a new major version a couple months ago.](https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/CHANGELOG.md)

This new version has several new useful checks, so it would be great if the config could be updated to use this version.

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
you'll also need to change the peer deps entry.

**Comment by ptmkenny** [comment]
Thanks for the quick feedback!  I updated the peer dependency.

**Review by anandfresh — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Comment by renchris** [comment]
How do we use this? The current release version is 19.0.4 from Dec 25, 2021.

**Comment by ljharb** [comment]
@renchris you don't use it, until it's released, which it's not yet (it was only merged 2 days ago)

**Comment by renchris** [comment]
With the current and last package release being a few years ago, what is a rough timeframe expectation for the next release containing this update to be?

**Comment by ljharb** [comment]
There's no expected timeframe and no release schedule, and the time since the last release has no bearing on anything - no release has been needed since the last one, and the next one will include full eslint 9 support. feel free to follow #2961 for updates.

**Comment by ptmkenny** [comment]
@renchris If you want to use this now, if you're using npm, you can install `eslint-plugin-react-hooks` 5 with `--force`.  That will override the v4 specified by the current release.

**Comment by renchris** [comment]
Thank you, you two. I will override the peer dependency `eslint-plugin-react-hooks` version 5 with `--force` now and follow the https://github.com/airbnb/javascript/issues/2961 thread for the next eslint v9 version with this update as well

**Pull request merged**
