### PR TITLE
Enable all rules marked with TODO: enable

### PR DESCRIPTION
**Pull request by lencioni**
We had a few of these queued up as breaking changes. Now that we are
getting ready to release, we can enable them.

### CODE REVIEW

**Comment by ljharb** [comment]
Are there guide sections covering all of these rules yet?

**Comment by lencioni** [comment]
Good question. I guess I assumed there were since they were marked as TODO: enable. I'll poke around soon.

**Comment by ljharb** [comment]
the "todo" was meant to include writing the guide sections :-)

**Comment by lencioni** [comment]
This is a bit more involved than I'd like at this moment, so I'm going to close this out. Perhaps I'll come back to this one rule at a time.

**Pull request closed without merging**
