### PR TITLE
[chore] Remove country flags for translation list

### PR DESCRIPTION
**Pull request by lizheming**
It doesn't suitable that add a country flags near by language name. Because a language may be used by many of countries.

### CODE REVIEW

**Comment by ljharb** [comment]
That's a reasonable take, but it's visually nice to have icons to identify them, and flags are the closest thing to a language icon we have.

Do you have a better suggestion?

**Comment by lizheming** [comment]
@ljharb I think there has no icon can represent a language name. But let we think about it another way, why we need a nice icon for a translation list? If we have no applicable to express them, why not remove them? At last, I think the right infomation is more important than nice style for a standard repo.

ps. Let we look at wikipedia, it also hasn't language icon at language list.

image

**Comment by ljharb** [comment]
I'm not sure I find that convincing.

What's the downside to having the flags here?

**Comment by lizheming** [comment]
@ljharb For example, both [South Korea](https://en.wikipedia.org/wiki/South_Korea#Language) and [North Korea](https://en.wikipedia.org/wiki/North_Korea#Language) are use Korea language, but their country flags are difference. Same situation like [Germany](https://en.wikipedia.org/wiki/Germany#Languages) and [Austria](https://en.wikipedia.org/wiki/Austria#Language) both use german language, [Argentina](https://en.wikipedia.org/wiki/Argentina#Languages) and [Mexico](https://en.wikipedia.org/wiki/Mexico#Languages) and [Spain](https://en.wikipedia.org/wiki/Spain#Languages) both use Spanish language. It's not suitable to use one country flag represent language name.

**Comment by ljharb** [comment]
Sounds like an argument to include multiple country flags rather than just removing them?

**Comment by lizheming** [comment]
@ljharb every national language may have different count countries, I think both country flags add to list may misaligned. So i think remove them is better than add all of country flags.

**Comment by ljharb** [comment]
True. The list could instead be turned into a table, though, which would address that problem without having to remove any flags.

**Comment by lizheming** [comment]
@ljharb I can't agree with table solution. The main purpose for translation list just a link that we can go to translation repo, It's not emphasis for our repo. Is it too heavy for us that a table which has both countries flags?

**Comment by ljharb** [comment]
That purpose is served by providing a visual cue so readers can quickly find the language they're looking for in the list.

**Comment by lizheming** [comment]
@ljharb A language list is enough to visualize to user find target. I think more and more flag icons would make user dazzling. If you still decide to use table, I still respect it~

**Comment by ljharb** [comment]
I think the only change that makes sense here is adding any missing flags, and converting to a table so alignment is preserved.

**Pull request closed without merging**
