### PR TITLE
[spam]

### PR DESCRIPTION
**Pull request by rkmukherjee**
hey just ignore this. I did this just for learning

### CODE REVIEW

**Comment by ljharb** [comment]
It’s spam, not learning.

**Comment by rkmukherjee** [comment]
Thank you for not understanding. 🙂. I was learning how to contribute towards a code base.
________________________________

**Comment by ljharb** [comment]
Then you haven’t learned the right thing, because making one useless PR to someone else’s is worse than a thousand people not learning how GitHub works. 

If you want to learn, make a repo just for learning purposes.

**Comment by rkmukherjee** [comment]
Really sorry for the mess, I was just following my teacher. ---------- Forwarded message ----------From: Jordan Harband ***@***.***>Date: Feb 16, 2024 9:44 PMSubject: Re: [airbnb/javascript] [spam] (PR #2902)To: airbnb/javascript ***@***.***>Cc: "Rohan Kr. Mukherjee" ***@***.***>,Author ***@***.***>
Then you haven’t learned the right thing, because making one useless PR to someone else’s repo is worse than a thousand people not learning how GitHub works.
If you want to learn, make a repo just for learning purposes.

**Comment by ljharb** [comment]
Then the teacher should be ashamed.

Is it vishwa's youtube video? That's the one I know of that points here.

**Pull request closed without merging**
