### PR TITLE
Please ignore this

### PR DESCRIPTION
**Pull request by itisRamzan**
Please ignore this, this is just for learning PR.

### CODE REVIEW

**Comment by ljharb** [comment]
No, it's not for learning, it's spam. Learn on your own repos.

**Comment by itisRamzan** [comment]
> No, it's not for learning, it's spam. Learn on your own repos.
Thank you for the clarification. I genuinely had no intention to spam and neither knew opening a PR for "learning PR" is a spam, as I was just intending to follow a learning course, and I appreciate your guidance. Learning from this experience, and I'll ensure to contribute more thoughtfully in the future.

**Comment by ljharb** [comment]
@itisRamzan it's fine as long as you can tell me what the learning course is, or link to it :-)

**Comment by itisRamzan** [comment]
This was the video I was following "https://www.youtube.com/watch?v=e0rl2PetMIY&t=2s&ab_channel=PWSkillsTech", I've seen from the previous invalid PRs here that it can cause a lot of spam. I'll ensure to contribute more thoughtfully in the future and focus on meaningful additions to the project :-)

**Comment by ljharb** [comment]
Thanks, I appreciate that!

**Comment by ljharb** [comment]
@vishwa07dev please edit your video so we can stop getting this onslaught of spam.

**Pull request closed without merging**
