### PR TITLE
Add `hasOwn` to section 3.7

### PR DESCRIPTION
**Pull request by maurer2**
Discussion related to this pr: https://github.com/airbnb/javascript/issues/2606

### CODE REVIEW

**Review by cyrus303 — APPROVED** [review]
upgrade looks good

**Review by ljharb — CHANGES_REQUESTED** [review]
We should wait to land this until airbnb-js-shims is using https://npmjs.com/object.hasown or similar

**Comment by ljharb** [comment]
@maurer2 since you deleted the fork, this sadly can never be merged.

**Comment by maurer2** [comment]
Sorry, totally forgot to close this before deleting the repo.

**Comment by ljharb** [comment]
Closing it first wouldn't have helped; until a PR is merged (or closed as a wontfix) the fork can't ever be deleted, or the PR is unrecoverable.

**Comment by maurer2** [comment]
Okay, I see. I can recreate the pr, if it still makes sense to add this to the style guide. 

Cheers

**Comment by ljharb** [comment]
At this point let's just leave it as is; it's not clear if airbnb-js-shims is maintained or not.

**Pull request closed without merging**
