### PR TITLE
add note about install-peerdeps to readmes

### PR DESCRIPTION
**Pull request by nathanhleung**
discussed in #1233, windows users can use install-peerdeps to automatically install peerdeps for the config

### CODE REVIEW

**Comment by SimenB** [comment]
Could something other than `#` be used? It's rendered as comments.

image

**Comment by ljharb** [comment]
Sure, suggestions welcome - I just don't want it to be a valid command

**Comment by nathanhleung** [comment]
@SimenB  If you omit the ```sh at the start of the block it'll disable the syntax highlighting:

With ```sh
```sh
npm install --save-dev eslint-config-airbnb eslint@^#.#.# eslint-plugin-jsx-a11y@^#.#.# eslint-plugin-import@^#.#.# eslint-plugin-react@^#.#.#
```

Without ```sh
```
npm install --save-dev eslint-config-airbnb eslint@^#.#.# eslint-plugin-jsx-a11y@^#.#.# eslint-plugin-import@^#.#.# eslint-plugin-react@^#.#.#
```

Do you want to submit a PR for that?

**Comment by ljharb** [comment]
Sure, that seems fine too.

**Comment by vamsiampolu** [comment]
@ljharb the install script is really great, but I noticed two things:

+ it does not install them as dev dependencies

+ it does not install the `eslint-config-airbnb` package itself

So, I made a few changes:

```sh
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g ' | xargs npm install --save-dev;
  npm install eslint-config-airbnb --save-dev
)
```

**Comment by ljharb** [comment]
@vamsiampolu As you can see [here](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1) and [here](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#eslint-config-airbnb-base-1), the command is:
```sh
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

which already absolutely installs the package itself, and installs everything as dev dependencies.

**Pull request merged**
