### PR TITLE
Updated "In The Wild" to include Brainshark.

### PR DESCRIPTION
**Pull request by dbowsbsk**
Hey Airbnb - We here at Brainshark are now using your excellent style guide and want to be included on the "In The Wild" list.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks! Would you mind rebasing this on the latest master?

**Comment by dbowsbsk** [comment]
Hey Jason - I merged with the latest commits.  Is this what you needed?

**Comment by dbowsbsk** [comment]
Oops - sorry Jordan for calling you Jason :)

**Comment by ljharb** [comment]
@dbowsbsk close - if you could run `git rebase` locally so that there's just one commit on top of the latest master, that would be ideal. if not, i can do it manually, but the git log ends up nicer this way :-)

**Comment by dbowsbsk** [comment]
ah ok. thx.

**Comment by dbowsbsk** [comment]
Ok - Does that look correct?

**Comment by ljharb** [comment]
You'll need to force push to get your newest changes up

**Comment by dbowsbsk** [comment]
Ok I did a git push -f and it said everything is up to date.  Are you seeing the changes now?

**Comment by ljharb** [comment]
@dbowsbsk in that case i don't think you did the rebase correctly - i'll cherry-pick this one in, no worries

**Comment by ljharb** [comment]
Merged in with 30c448d1df2c5a16bee4dd618ebdcf908b7475a3

**Comment by dbowsbsk** [comment]
Thanks! Sorry about that.

**Pull request closed without merging**
