### PR TITLE
Document corresponding jscs rules

### PR DESCRIPTION
**Pull request by fxmaxvl**
add ref to jscs rule: [disallowArrayDestructuringReturn](http://jscs.info/rule/disallowArrayDestructuringReturn)

### CODE REVIEW

**Comment by ljharb** [comment]
Would you mind rebasing this on latest master?

**Comment by fxmaxvl** [comment]
done

**Comment by ljharb** [comment]
@fxmaxvl that actually was a merge (note the merge commit https://github.com/fxmaxvl/javascript/commit/af68d229086a34acc86127d71bad17d0e6c1060a) - can you rebase instead, leaving behind 1 commit directly on top of latest master?

**Comment by fxmaxvl** [comment]
second try

**Comment by ljharb** [comment]
Thanks!

**Pull request merged**
