### PR TITLE
Remove wrong example for 11.1

### PR DESCRIPTION
**Pull request by apsavin**
Removed example had nothing in common with the "Why" section and was too much like "bad" one.

### CODE REVIEW

**Comment by ljharb** [comment]
The (not wrong) example shows the evolution from loops, to forEach, to functional iteration methods. I'd prefer to keep it.

**Comment by apsavin** [comment]
But there is no sense in such evolution - from for loop with side effect to forEach with side effect.

**Comment by km256** [comment]
>The (not wrong) example shows the evolution from loops, to forEach, to functional iteration methods. 

But why it's better?

**Comment by apsavin** [comment]
correctly used `for` loop -> bad usage of functional iteration method -> good usage of functional iteration method

Sorry, but I just can't get it.

**Comment by ljharb** [comment]
@apsavin i understand you don't see the sense in it - however, that progression is exactly the way many people learn functional patterns. `forEach` is similar enough to a `for` loop that it serves as a good stepping stone to learning about `map`, `filter`, etc.

**Comment by jifeon** [comment]
maybe just replace `good` with `better`

**Comment by apsavin** [comment]
@ljharb makes sense, thanks.

**Pull request closed without merging**
