### PR TITLE
Updates peerDependencies for eslint-config-airbnb

### PR DESCRIPTION
**Pull request by kamronbatman**
Updates peerDependencies for eslint-config-airbnb.
Also since the last NPM release has a severely outdated peerDependency for eslint-plugin-jsx-a11y, can we please get a new NPM release with this update?

Thanks!

### CODE REVIEW

**Comment by ljharb** [comment]
v2 to v3 of eslint-plugin-jsx-a11y is not "severely" outdated; if you read the changelog you'll see the differences are minor.

It is explicitly intentional to not yet have released an update of `eslint-config-airbnb` that supports v3 of `eslint-plugin-jsx-a11y`, and I will release an update when it is ready.

Thanks for the contribution; I'll rebase it down to one commit with the desired commit message convention, and merge it in.

**Comment by ljharb** [comment]
A better solution imo is to never globally install anything, especially a linter, which should always only be installed per-project :-)

**Comment by kamronbatman** [comment]
I agree that is an option.  It is definitely a pain in the ass when it comes to IDE setup.  Webstorm in particular is not smart enough to say... 'Lets find the project root directory, lets find the rc file, then lets find node_modules, then lets find eslint'.

You are right though, just need to manually set it up, sigh.

**Comment by ljharb** [comment]
Just published v14.0.0 of the main config, and v11.0.1 of the base config.

(#1162, #1166, #1182, #1186, #1207, #1212, #1222)

**Pull request merged**
