### PR TITLE
A simple JavaScript code to help the public or an individual to customize and build your personal CSS framework

### PR DESCRIPTION
**Pull request by emmanuel-455**
Simple JavaScript code that can give developers and insight on how to build and customize their own CSS framework and use it on their personal projects.

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
This doesn’t belong in this document or this repo; and we assume you’re using react.

**Comment by ljharb** [comment]
Also, please don’t send unsolicited PRs to any repo without first confirming it’s wanted.

**Comment by emmanuel-455** [comment]
> Also, please don’t send unsolicited PRs to any repo without first confirming it’s wanted.

Sorry about that. Just tryna make a lil contribution

**Comment by emmanuel-455** [comment]
> This doesn’t belong in this document or this repo; and we assume you’re using react.

This is javascript only

**Comment by ljharb** [comment]
That’s a great instinct! Contributions need to fit the project, though. What were you trying to achieve with this specific content? Why would it be a good idea for someone to roll their own framework?

**Comment by emmanuel-455** [comment]
I just figured it out and I wanted to share it. My bad if I did something wrong🙏

**Comment by ljharb** [comment]
I'm still not clear on what you figured out - that you can dynamically walk the DOM and read/write styles? It's a long way between that and a CSS framework.

**Comment by emmanuel-455** [comment]
> I'm still not clear on what you figured out - that you can dynamically walk the DOM and read/write styles? It's a long way between that and a CSS framework.

I'm a self thought upcoming programmer and I just figured I could just customize my class value to perform some specific styling by just using javascript only. But I made mistakes by calling it CSS framework

**Comment by emmanuel-455** [comment]
> > I'm still not clear on what you figured out - that you can dynamically walk the DOM and read/write styles? It's a long way between that and a CSS framework.
> 
> I'm a self thought upcoming programmer and I just figured I could just customize my class value to perform some specific styling by just using javascript only. But I made mistakes by calling it CSS framework

Sorry if that sound childish to u but I'm just an upcoming programmer🙏

**Pull request closed without merging**
