### PR TITLE
22.3: Add Link to eslint rule.

### PR DESCRIPTION
**Pull request by simono**

### CODE REVIEW

**Comment by ljharb** [comment]
Would you mind rebasing this onto latest master? Also, if you have other similar rule link additions, it'd be great to combine them into one PR

**Comment by simono** [comment]
I've rebased it.

Sorry for the two PRs…

**Comment by ljharb** [comment]
np - it'll need another rebase after #677 tho.

**Comment by simono** [comment]
Done :)

**Pull request merged**
