### PR TITLE
[readme] add space before code blocks

### PR DESCRIPTION
**Pull request by Pushpendra100**
**space added before code-block**

***Before***
Screenshot (1053)

***After***
Screenshot (1054)

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Why?

**Comment by ljharb** [comment]
I’m not sure how - we don’t use p tags on all the other sections.

**Comment by Pushpendra100** [comment]
> I’m not sure how - we don’t use p tags on all the other sections.
This is a hacky way to get it displayed correctly. An empty p-tag won't be rendered to anything visible, and it will also add space.

**Comment by ljharb** [comment]
ok, i think i see the problem you're trying to fix. If the goal is to get a newline, and an actual markdown newline won't work, then i'd expect `<br />`.

Is this just because of the bulleted list followed by a code block?

**Comment by Pushpendra100** [comment]
> Is this just because of the bulleted list followed by a code block?

Yes, a new markdown line is not added when a code block follows a list in the markdown.  So, we can also put <br> tag between the list and code-block.

It will look like this
Screenshot (1056)

**Comment by Pushpendra100** [comment]
> alrighty, let's update it to use `<br />` (with the proper xhtml closing slash) and we can get this in.

Ya, I have made the required changes, you can review it.

**Comment by Pushpendra100** [comment]
Hey, can I ask why you haven't merged it till now?

**Comment by ljharb** [comment]
Because I'm a human with a personal life, and I've been on vacation. Please be patient; PRs can take months or years to be merged, and that's perfectly OK.

**Comment by Pushpendra100** [comment]
> Because I'm a human with a personal life, I've been on vacation. Please be patient; PRs can take months or years to be merged, and that's perfectly OK.

Sorry for the inconvenience. No problem you can take your time and enjoy your day.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
