### PR TITLE
Support eslint-plugin-import 2.x.x Fixes #1107

### LINKED ISSUE #1107: upgrade eslint-plugin-import to 2.0.0

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by ljharb** [comment]
Duplicate of #1101, #1104.

**Comment by graingert** [comment]
@ljharb sorry I searched for "eslint-plugin-import 2" in the issues

**Comment by graingert** [comment]
@ljharb this would not be a breaking change, but would allow me to upgrade and add my own config overrides. Can you accept this PR sooner than #1101 ?

**Comment by ljharb** [comment]
There's no hurry in upgrading.

**Comment by ljharb** [comment]
`eslint-config-airbnb` `v13.0.0` is now released.

**Pull request closed without merging**
