### PR TITLE
Support unused vars

### PR DESCRIPTION
**Pull request by Runrioter**
Sometimes, I will have the following code:
```javascript
const express = require('express');

const router = express.Router();
router.get('/', (req, res, next) => {
  res.render('index', { title: 'Express' });
});
```
Currently, `next` is not used, so I want to support it like this:

```javascript
const express = require('express');

const router = express.Router();
router.get('/', (req, res, _) => {
  res.render('index', { title: 'Express' });
});
```
And underscore is natively for unused variable for programming language like Swift.
```swift
func f(p :String, _ :String) {
       // ...
}
```

I think that `_` is a good choice.

### CODE REVIEW

**Comment by ljharb** [comment]
If it's not used, why name it in the signature?

**Comment by Runrioter** [comment]
Ok, You are right. 
But I think that keeping function signature(middleware from some web framework) consistent is better and readable.
And sometimes unused var can't be omitted. For example:
```javascript
try {
    const obj = JSON.parse(str);
    return obj;
} catch (_) {
    return null;
}
```

**Comment by Runrioter** [comment]
@ljharb  Seems that you think that it is unnecessary, I maybe need to make a new repo or just override some eslint rule in config file. Thank you.

**Comment by ljharb** [comment]
When the unused var *can't* be omitted, eslint will allow it.

**Pull request closed without merging**
