### PR TITLE
Support eslint flat config

### PR DESCRIPTION
**Pull request by OlivierZal**

### CODE REVIEW

**Comment by OlivierZal** [comment]
Blocked by https://github.com/import-js/eslint-plugin-import/pull/2873

**Comment by Pilaton** [comment]
@ljharb, It would be worth adopting this PR, if only as a temporary solution to support a flat configuration. 🤷‍♂️

**Comment by ljharb** [comment]
@Pilaton a temporary solution would be worse than no solution at all, so it remains blocked.

**Comment by rarenatoe** [comment]
@OlivierZal @Pilaton @ljharb 2 days ago flat config was allowed for eslint-plugin-import

https://github.com/import-js/eslint-plugin-import/releases/tag/v2.30.0

**Comment by ljharb** [comment]
There's no need to close and delete the PR - it's just not quite time to land it yet.

**Pull request closed without merging**
