### PR TITLE
[spam]

### PR DESCRIPTION
**Pull request by ChittaranjanTanty**
hey ,you can ignore this pr.
i did this just to learn how to raise a pr.

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
This is spam.

**Comment by ChittaranjanTanty** [comment]
Sir, kindly remove the spam. I am new to GitHub.I am a BTech student. Actually the instructor of the training in which I have enrolled was using this repository. So I also did. And there is nothing in it. Just an added file in which it's written that I am learning how to pr

**Comment by ljharb** [comment]
Yea, that’s still spam. Your instructor is teaching a very bad thing.

**Comment by ChittaranjanTanty** [comment]
I apologies for it will never repeat again. Please remove the spam.🙏

**Comment by ljharb** [comment]
PRs are permanent, so it’ll be spam forever, I’m afraid.

**Comment by ChittaranjanTanty** [comment]
please sir make this exception for me. I am a new user. Oneway you helped
me to learn about github policies. thank you so much about for that. now i
will go for the entire guideline in github. but sir please remove this spam
flag. it discourages and demotivates me.

**Pull request closed without merging**
