### PR TITLE
Patch ukrainian translation

### PR DESCRIPTION
**Pull request by ivanzusko**

### CODE REVIEW

**Comment by oshalygin** [comment]
That is a lot of commits, rebase?

**Comment by ivanzusko** [comment]
@oshalygin hope this is ok

**Comment by ljharb** [comment]
@ivanzusko almost! Ideally it'd include no merge commits and be a single commit. If you'd mind rebasing it that'd be great, if not, I can do it for you

**Comment by ivanzusko** [comment]
@ljharb no-no, I'll do it by myself :) just never done it before. Good reason to learn something new :+1:

**Comment by ivanzusko** [comment]
@ljharb the best I managed to do so far is two commits instead of three...

**Pull request merged**
