### PR TITLE
Corrected case

### PR DESCRIPTION
**Pull request by BusbyActual**
Updated case to read the same in multiple spots. Added single quote example

### CODE REVIEW

**Comment by ljharb** [comment]
@BusbyActual looks good! Would you mind rebasing down to a single commit?

**Comment by BusbyActual** [comment]
Can do looking into how. I've never updated a pull request before this should be exciting

**Comment by BusbyActual** [comment]
@ljharb I'm not quite sure how to make those changes on an open PR so it might be easier for me to close and open a new PR with the requested changes.

**Comment by ljharb** [comment]
@BusbyActual no need - i'll rebase it for you :-)

**Comment by BusbyActual** [comment]
@ljharb You're the best man! <3

**Pull request merged**
