### PR TITLE
Airbnb React/JSX Style Guide translation for PT-BR

### PR DESCRIPTION
**Pull request by ronal2do**
Translate for PT-BR

### CODE REVIEW

**Comment by ljharb** [comment]
@ronal2do Thanks! would you be able to squash these down to one commit?

**Comment by ljharb** [comment]
(linking to #954)

**Comment by hshoff** [comment]
These are my favorite kind of PRs. Thanks for this @ronal2do!

**Comment by ronal2do** [comment]
This new link.
https://github.com/ronal2do/airbnb-react-styleguide

**Pull request merged**
