### PR TITLE
[resources] add link to neutrino preset

### PR DESCRIPTION
**Pull request by hshoff**
[Neutrino](https://neutrino.js.org/) is a cool new project from Mozilla for creating and building modern JS apps with zero configuration.

[What is the added value versus all the boilerplate projects out there like create-react-app?](https://neutrino.js.org/FAQ.html#what-is-the-added-value-versus-all-the-boilerplate-projects-out-there-like-create-react-app) is worth a read.

Neutrino already has an Airbnb base preset here: https://neutrino.js.org/presets/neutrino-preset-airbnb-base/ and supports customization as outlined in this "turning off semis required" example: https://neutrino.js.org/presets/neutrino-preset-airbnb-base/#simple-customization

### CODE REVIEW

**Comment by ljharb** [comment]
Who maintains this preset?

Why does it need to be different than the eslint config? Does neutrino use something different from eslint for linting and autofixing?

**Comment by hshoff** [comment]
@ljharb it's a [neutrino config module](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-airbnb-base/src/index.js) that makes it easy to add ESLint and set the rules to the Airbnb base preset for a neutrino project. [package.json](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-airbnb-base/package.json#L17)

Looks like it's maintained by @eliperelman (:wave: Hi Eli)

**Comment by ljharb** [comment]
That package.json is lacking the proper peer dependencies - `eslint-plugin-import` is required for the base config, for example, and eslint itself needs to be available with the proper version.

**Comment by hshoff** [comment]
that comes from the [neutrino-lint-base](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-lint-base/package.json) package

**Comment by eliperelman** [comment]
@hshoff hello!

> Why does it need to be different than the eslint config? Does neutrino use something different from eslint for linting and autofixing?

No, we don't use something different, it's merely a preset for plugging in the Airbnb style guide into a Neutrino project, which is Webpack-based. Behind the scenes it is still using the eslint-loader and thereby ESLint.

Put simply, it gives Neutrino users a fast path to lint quality via `yarn add --dev neutrino-preset-airbnb-base`, and adding it to their list of other presets. I'd be happy to answer any questions if you have any.

**Comment by ljharb** [comment]
@eliperelman thanks for the explanation! the dependencies still need to be fixed (`npm install neutrino-preset-airbnb-base && npm ls` will exit nonzero) but that all makes sense.

**Pull request merged**
