### PR TITLE
Adds new examples to iterators section

### PR DESCRIPTION
**Pull request by sara-gudeman**
closes issue #1068

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks!

**Comment by churchie317** [comment]
Not to be pedantic, but should we consider calling the mutated arrays something other than `modified`? Can I recommend `newArray`?

I just wonder if it might confuse newer users who would think that it's the original arrays that are being modified.

**Comment by ljharb** [comment]
Sure, a different name is fine. Maybe instead of `newArray`, something like `increasedByOne`?

**Comment by churchie317** [comment]
#1202 Hope this helps!

**Pull request merged**
