### PR TITLE
Docsify page

### PR DESCRIPTION
**Pull request by diomed**
I thought it would be nice to have HTML version of repository so I docsified it. 

docsify uses README file to create web page content which can be displayed in github pages.
so you can enter link in description of repository and content will then be displayed as standalone web page like it is in my repo:
[preview here](https://diomed.github.io/javascript)

Cheers!

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
Thees already one; it’s linked from the repo.

Either way we’d never want the html committed, because then there’s 2 sources of truth.

**Comment by diomed** [comment]
what do you mean by 'there's 2 sources of truth?'

**Comment by ljharb** [comment]
When the guide is updated, it has to be changed in two places.

Generated output doesn’t ever belong committed to source control..

**Comment by diomed** [comment]
> When the guide is updated, it has to be changed in two places.
> 
> Generated output doesn’t ever belong committed to source control..

no. you don't seem to understand. it doesnt have to be changed in two places. 
this is HTML version of content of your README file.  when you update readme, docsify just generates webpage with content of your readme. that's the beauty of it.

**Comment by diomed** [comment]
I also don't see this link anywhere

> Thees already one; it’s linked from the repo.

**Comment by ljharb** [comment]
If it’s generated, it doesn’t belong in the repo.

https://airbnb.io/javascript/ (you’re right tho, we don’t link to it because the markdown is a better experience)

**Comment by diomed** [comment]
allright, thanks for pointing out existence of it to me. I was unaware. 
that link should be in repo description, tho. so it's anyone's choice how they're gonna see it. 

✌️ 

thank you for creating this very useful repository. cheers!

**Comment by ljharb** [comment]
It’s not there because we prefer people to use the markdown.

**Pull request closed without merging**
