### PR TITLE
fix(README): replace wrong word (Enforce) with the right one (Avoid)

### PR DESCRIPTION
**Pull request by vaishnavyogesh**
Replace Enforce with Avoid to make the correct statement.

### CODE REVIEW

**Comment by ljharb** [comment]
Enforce isn’t the wrong word here.

**Comment by vaishnavyogesh** [comment]
image

The code above says **Enforce spacing inside of computed property brackets** but there is no spacing inside the brackets in the code section commented as **good**

**Comment by vaishnavyogesh** [comment]
@ljharb ^

**Comment by ljharb** [comment]
“Enforce” can mean either “require” or “forbid”.

**Comment by vaishnavyogesh** [comment]
Okay! thank you for clarification

**Pull request closed without merging**
