### PR TITLE
[eslint config] [base] remove unneeded eslint version check

### PR DESCRIPTION
**Pull request by PaperStrike**
As eslint < 7 is dropped in #2495 :)

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks, the breaking change was unfortunate.

**Comment by n-studio** [comment]
We should release this change as 15.0.1 to solve https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

**Comment by ljharb** [comment]
That isn’t actually a vulnerability here, and we’re on v19 - we won’t be back porting anything to v15.

**Comment by n-studio** [comment]
@ljharb Sorry I was referring to the package https://www.npmjs.com/package/eslint-config-airbnb-base, not https://www.npmjs.com/package/eslint-config-airbnb, it hasn't a v19 release, right?

**Comment by n-studio** [comment]
@ljharb Ok, no problem. I like fixing CVE alerts even if they are false positive so the CI doesn't block my releases. In the meanwhile I'll just load my package from master.

**Comment by ljharb** [comment]
I strongly discourage doing that; there's no guarantee everything will work.

If your CI is blocking releases on false positive CVEs, i'd invite you to consider that it's not actually making your project more secure, but less.

**Pull request merged**
