### PR TITLE
[react] inline export syntax

### PR DESCRIPTION
**Pull request by gilbox**
b more 1337

### CODE REVIEW

**Comment by justjake** [comment]
LGTM, but this may be controversial with the original guide authors? Some people complained about having exports other than at the very bottom of the file.

**Comment by ljharb** [comment]
In this specific case, I like this change, because 100% of the code below the default export is something that will be moved into inline `static` properties at some point. In all other cases, I'd want the exports to be the final thing in any file. However, I'm not sure if the inconsistency is clearly explained.

**Comment by gilbox** [comment]
If the goal is to place all exports at the bottom, then [at least one](https://github.com/airbnb/javascript/tree/master/react#ordering) code example needs to be updated.

**Comment by goatslacker** [comment]
yeah sure

**Comment by ljharb** [comment]
(I opened https://github.com/airbnb/javascript/pull/492 to fix that code example)

**Comment by justjake** [comment]
I'm merging this because I agree and discussion stopped.

**Pull request merged**
