### PR TITLE
docs: babel-eslint not neede since 1.0.0 any more

### PR DESCRIPTION
**Pull request by joscha**

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks! I forgot about this :-)

**Comment by gausie** [comment]
This unfortunately means that babel transforms I use are now marked as invalid by eslint.

**Comment by helielson** [comment]
https://github.com/airbnb/javascript/issues/589

**Comment by hbrls** [comment]
@gausie How did you fix it? I have

      "parser": "babel-eslint",
      "extends": "airbnb",

but it seems that airbnb ignored the parser.

**Comment by ljharb** [comment]
@hbrls it seems the latest version of eslint (2.10.0) has a bug where it ignores the parser setting. Try `2.9.x`.

**Comment by hbrls** [comment]
@ljharb Thx! It's working now.

**Pull request merged**
