### PR TITLE
[strings] 80 char => 100 char

### PR DESCRIPTION
**Pull request by hshoff**
Let's be consistent with our Ruby style guide: https://github.com/airbnb/ruby#line-length

@goatslacker @ljharb @justjake

### CODE REVIEW

**Comment by goatslacker** [comment]
-1 How about we make the ruby one 80? This

**Comment by BMorearty** [comment]
+1 for 100 char line length.

**Comment by ljharb** [comment]
None of us are on 9" terminals. I'd vote for 120 :-) but 100 is fine.

Complexity, not length, should be the thing we strive to reduce - whether it's in lines, or anything else.

**Comment by hshoff** [comment]
Sorry @goatslacker, I'm going for it. :smile:

**Pull request merged**
